name: CI

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    build-and-push-docker:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
            IMAGE_NAME: mohit14336/mern-pizza-app-auth-service
            IMAGE_TAG: build-${{ github.run_number }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Build Docker Image
              run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f docker/prod/Dockerfile .

            - name: Push Docker Image to Docker Hub
              run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
